### ISSUE TITLE
local version not working with sublimetext rubocop

### ISSUE THREAD

**Issue by gabpaladino** [asdf-vm/asdf-ruby#56] opened 2017-12-23 17:49 UTC
Hello.

I'm getting error on my sublime linter rubocop, when running `/Users/gabriel/.asdf/shims/ruby -S rubocop --version` gets a `No version set for ruby` message.

Only works after set a global ruby version.

**Comment by Stratus3D** [comment] 2018-02-14 16:42
What happens if you run `asdf reshim ruby`? I'm not sure what the issue is, but make sure you have the right Ruby version installed with asdf (`asdf install ruby <version>`) and also make sure your project directory is set to use that same version.

**Comment by gabpaladino** [comment] 2018-02-15 11:18
Same thing with reshim. I have corrects ruby versions, setting a global ruby it works, but without global i think it's not looking for correct project path for get ruby version.

![image](https://user-images.githubusercontent.com/370163/36254052-c9a2c39e-1230-11e8-9f85-824ed2789c74.png)

**Comment by Stratus3D** [comment] 2018-02-15 14:04
Yeah that's possible. asdf relies on the current working directory to set the version, so if SublimeLinter is running from some other directory then the version may not be set.

I'm not sure what OS you are on, but you should be able to find some details on the SublimeLinter process, including the directory in which it was started.

**Comment by Stratus3D** [comment] 2018-06-26 00:17
Closing this since I don't think there is anything asdf-ruby can do to fix this.

**Closed by Stratus3D** 2018-06-26 00:17 UTC

**Comment by gilbertek** [comment] 2018-08-08 21:54
I am not sure if this will help, run into similar issue, and here's how I solved it. 

I added a user setting file with the following (Sublime Text > Preferences > Package Settings > Rubocop > User - Settings)
```ruby
{
  // Note: If check_for_rvm and check_for_rbenv are both enabled,
  // the plugin will use RVM.
  "check_for_rvm": false,

  "check_for_rbenv": true,

  // The path to rbenv's binary
  "rbenv_path":  "~/.asdf/shims/rubocop",
}

**Comment by cerdiogenes** [comment] 2019-03-22 18:02
I just disabled rmv and check and used:

```json
{
	"check_for_rvm": false,
	"rubocop_command": "/home/kadu/.asdf/shims/rubocop"
}
```

**Comment by airtonix** [comment] 2022-06-25 08:37
This only works if your sublime text plugin does it's thing in the root of your project where your `.tool-versions` are.

If it's making assumptions about where its `cwd` is (like where ever it is that you executed `subl` then your shims still won't work because they rely on looking at `$(cwd)/.tool-versions`
