### ISSUE TITLE
Can't install any rails version with ruby 2.4.2 

### ISSUE THREAD

**Issue by fcbarbi** [asdf-vm/asdf-ruby#48] opened 2017-11-02 21:31 UTC
Hello. I am reaching out after a couple of days on this issue. Any insight is appreciated.

I am migrating (macOS is 10.12.6) from **rbenv** with the latest ruby 2.4.2 but there seems to be impossible to gem-install rails after a `gem uninstall rails` as I get the message to reinstall rails:
```
$ rails -v
Rails is not currently installed on this system. To get the latest version, simply type:
    $ sudo gem install rails
You can then rerun your "rails" command.

$ asdf current
ruby 2.4.2 (set by /Users/fcbarbi/.tool-versions)

$ ls /Users/fcbarbi/.asdf/shims
byebug		gem		listen		pumactl		rdoc		ruby		
sass-convert	spring erb		irb		puma		rake		ri		
sass		scss		tilt

$ gem install rails -v5.1.0
Fetching: activesupport-5.1.0.gem (100%)
Successfully installed activesupport-5.1.0
(...)
Fetching: railties-5.1.0.gem (100%)
Successfully installed railties-5.1.0
Fetching: rails-5.1.0.gem (100%)
Successfully installed rails-5.1.0
(...)
Done installing documentation for activesupport, actionview, actionpack, activemodel, activerecord, activejob, actionmailer, actioncable, railties, rails after 23 seconds
10 gems installed

$ asdf reshim ruby
```
All the other shims are installed but rails':
```
$ which gem 
/Users/fcbarbi/.asdf/shims/gem

$ which rake
/Users/fcbarbi/.asdf/shims/rake

$ which rails
/usr/bin/rails

$ rails -v
Rails is not currently installed on this system. To get the latest version, simply type:
    $ sudo gem install rails
You can then rerun your "rails" command.
```
I can't see why it does not create the shim, so I tried to manually set one copying one of the shims and editing it but this only changes the response to `which rails` that returns `/Users/fcbarbi/.asdf/shims/rails` but rails is not installed. 

I deleted the directories used by rbenv, `/Users/fcbarbi/.gem` and `/Users/fcbarbi/.rbenv` and I am sure it is completely uninstalled.

Any ideas would be welcome, mine are finished...

**Comment by abartier** [comment] 2017-11-16 16:42
Hello, 

Same problem here, resolved by: 

`asdf reshim ruby`

Hope it helps.

**Comment by nilbus** [comment] 2017-12-14 17:53
You may also have to restart your shell (alternately run `hash -r` if using bash) to update the path of the `rails` command.

**Comment by luizsignorelli** [comment] 2017-12-17 19:26
As @nilbus said, restarting the shell worked for me.

**Comment by Stratus3D** [comment] 2017-12-18 19:25
@fcbarbi what version of asdf are you using? (`asdf --version`)

**Comment by fcbarbi** [comment] 2017-12-18 23:00
Hello, thank you for the tips. 
Now I am using macOS is 10.13.2. Nothing else has changed in the configuration. We have:
"asdf --version" returns version v0.4.0. 
"which rails" returns "/Users/fcbarbi/.asdf/shims/rails" (problem solved? not yet...)
"asdf current" returns "ruby 2.4.2 (set by /Users/fcbarbi/.tool-versions)"
"ruby -v" returns "ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]"
But "rails -v" returns "No such command in 2.4.2 of ruby". 
Thank you for your feedback!

**Comment by Stratus3D** [comment] 2017-12-19 14:22
@fcbarbi odd. Maybe try `asdf reshim ruby 2.4.2`? I'm really not what the issue is. I use rails with asdf-ruby every week.

**Comment by Stratus3D** [comment] 2019-03-04 15:18
@fcbarbi asdf v0.7.0 is out, can you try upgrading and see if that fixes your issue? You'll also need to run `asdf reshim` after you upgrade.

**Comment by psantos10** [comment] 2019-06-07 09:11
Today I faced with the problem... 

after: `asdf reshim ruby` need to restart the Shell/Terminal to get it working

**Comment by kelvinromero** [comment] 2020-02-04 17:44
> Today I faced with the problem...
> 
> after: `asdf reshim ruby` need to restart the Shell/Terminal to get it working

This solved my problem

**Closed** 2020-02-18 12:43 UTC
