### ISSUE TITLE
Ruby 3.0

### ISSUE THREAD

**Issue by DevotionGeo** [asdf-vm/asdf-ruby#196] opened 2020-12-30 17:35 UTC
Why isn't Ruby 3.0 there?

**Comment by andypearson** [comment] 2020-12-30 18:13
This PR needs to be merged: https://github.com/asdf-vm/asdf-ruby/pull/192

For the moment you can do `ASDF_RUBY_BUILD_VERSION=v20201225 asdf install ruby 3.0.0` to get the new shiny Ruby :)

**Comment by Stratus3D** [comment] 2020-12-31 14:52
#192 has been merged. Closing this ticket.

**Comment by pmukerji** [comment] 2021-01-03 09:27
@Stratus3D - just a friendly ping that the issue is still open

**Comment by Stratus3D** [comment] 2021-01-03 22:09
Thanks @pmukerji closing for real this time :laughing:

**Closed by Stratus3D** 2021-01-03 22:09 UTC

**Comment by DevotionGeo** [comment] 2021-01-04 09:33
Thanks everyone!
