### ISSUE TITLE
bug: asdf list shows ruby `-l` as a version installed

### ISSUE THREAD

**Issue by kerolloz** [asdf-vm/asdf-ruby#234] opened 2021-11-12 10:18 UTC
### Describe the Bug

I have asdf-_**ruby**_ and asdf-_**nodejs**_ installed.
running `asdf list` shows `-l` as a ruby version installed
```shell
nodejs
  17.1.0
ruby
  2.7.4
  -l
```

### Steps to Reproduce

1. install asdf
2. install asdf-ruby
3. ` asdf install ruby -l`
4. `asdf install ruby 2.7.4`
5. `asdf list`

### Expected Behaviour

only show the installed version of ruby `2.7.4`

### Actual Behaviour

it shows that I have a version of ruby installed named `-l` 

### Environment

```shell
OS:
Linux Kerollos 5.13.0-21-generic asdf-vm/asdf#21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

SHELL:
GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

ASDF VERSION:
v0.8.1-a1ef92a

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/home/kerolloz/.asdf

ASDF INSTALLED PLUGINS:
nodejs                       https://github.com/asdf-vm/asdf-nodejs.git
ruby                         https://github.com/asdf-vm/asdf-ruby.git
```

**Comment by kerolloz** [comment] 2021-11-12 22:22
@Stratus3D Okay great, thank you. I hope it gets fixed soon. Let me know if I can help. I took a quick look at the source code here but didn't get where the bug comes from.

**Comment by Stratus3D** [comment] 2021-11-15 16:13
Ok, so I figured out what the issue is here. The code at fault was this line:

```
  echo "$patches" | $(ruby_build_path) ${opts} "$version" "$install_path"
```

Normally `$version` is a Ruby version that exists, that ruby-build locates and builds. But in your case `-l` isn't a ruby version, and ruby-build interprets it as the list versions flag, so rather than failing due to a missing version, ruby-build lists all available versions and exits successful. asdf itself assumes the successful exit means that ruby `-l` was installed successful.

Working on a fix for this now.

**Comment by Stratus3D** [comment] 2021-11-15 16:38
@kerolloz can you test out the PR I created to fix this issue?

**Closed** 2021-11-25 16:41 UTC
